language: cpp
sudo: true

# Cache homebrew downloads for osx
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - bin

addons:
  homebrew:
    packages:
      - shellcheck
  apt:
    packages:
      - shellcheck

os:
  - linux
  - osx

script:
  - ./ci.sh
