language: cpp
sudo: true

# # Grab shellcheck from the Debian repo 
# addons:
#   apt:
#     sources:
#     - debian-sid 
#     packages:
#     - shellcheck

install:
- sudo apt-get install shellcheck
- mkdir -p bin
- wget "https://github.com/github/hub/releases/download/v2.5.0/hub-linux-amd64-2.5.0.tgz" -O /tmp/hub.tar.gz
- tar -xvf /tmp/hub.tar.gz
- export PATH=$PATH:$PWD/hub-linux-amd64-2.5.0/bin/

script: 
- ./proj ci
